import { DEFAULT_GRADE, GRADE_INPUT_MODES } from "../services/gpa";

/**
 * Sensible defaults for the semester-based GPA calculator.
 *
 * - INITIAL_COURSES_PER_SEMESTER is the number of empty course rows we
 *   seed each new semester with so users have something to fill in right
 *   away. We start with 4 (the typical lower bound for a college term).
 * - MIN_COURSES_PER_SEMESTER controls how far users can shrink a
 *   semester — we keep 1 as the floor so removing a stray course always
 *   works, but the UI defaults to 4 on creation.
 * - MAX_COURSES_PER_SEMESTER is a soft upper bound to keep the layout
 *   readable.
 */
export const INITIAL_COURSES_PER_SEMESTER = 4;
export const MIN_COURSES_PER_SEMESTER = 1;
export const MAX_COURSES_PER_SEMESTER = 20;
export const MAX_SEMESTERS = 12;

/**
 * Toggle between viewing the currently-selected semester's GPA in the
 * meter UI vs the cumulative GPA across every semester.
 */
export const GPA_VIEW_MODES = {
  SEMESTER: "semester",
  CUMULATIVE: "cumulative",
};

function uid() {
  if (typeof crypto !== "undefined" && crypto.randomUUID) return crypto.randomUUID();
  return `id-${Date.now()}-${Math.floor(Math.random() * 1e9)}`;
}

export function createEmptyCourse(overrides = {}) {
  return {
    id: uid(),
    name: "",
    gradeInputMode: GRADE_INPUT_MODES.LETTER,
    grade: DEFAULT_GRADE,
    courseGpa: "",
    credits: 3,
    isAdvanced: false,
    ...overrides,
  };
}

/**
 * Create a brand-new semester pre-populated with INITIAL_COURSES_PER_SEMESTER
 * empty course rows. The label is generated by the caller so it can
 * use the next sequential number (e.g. "Semester 3").
 */
export function createEmptySemester(label, overrides = {}) {
  return {
    id: uid(),
    name: label,
    courses: Array.from(
      { length: INITIAL_COURSES_PER_SEMESTER },
      () => createEmptyCourse()
    ),
    ...overrides,
  };
}
